backend:
  name: gitlab
  repo: fidisys/website/web-revamp

publish_mode: editorial_workflow

media_folder: 'src/data/assets'
public_folder: '/'

collections:
  - label: Home
    name: home
    files:
      - label: Banner
        name: homeBanner
        file: 'src/data/home/banner.md'
        public_folder: '../assets'
        fields:
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: Services
        name: homeServices
        file: 'src/data/home/services.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Services
            name: services
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
      - label: Clients
        name: homeClients
        file: 'src/data/home/clients.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Clients
            name: clients
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
      - label: Works
        name: homeWorks
        file: 'src/data/home/works.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - label: Works
            name: works
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Description, name: description }
              - { label: Link, name: link }
              - { label: Image, name: image, widget: image }
      - label: SEO
        name: homeSeo
        file: 'src/data/home/seo.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
  - label: Testimonials
    name: testimonials
    files:
      - label: Testimonials
        name: testimonials
        file: 'src/data/testimonials.md'
        public_folder: './assets'
        fields:
          - { label: Title, name: title }
          - label: Customers
            name: customers
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Name, name: name }
              - { label: Message, name: message }
              - { label: Comment, name: comment }
              - { label: Role, name: role }
              - { label: Company, name: company }
              - { label: Image, name: image, widget: image }
  - name: blog
    label: Blog
    label_singular: 'Blog'
    folder: src/data/blog
    slug: '{{slug}}'
    create: true
    media_folder: ''
    public_folder: ''
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { name: author_image, label: Author Image, widget: image }
      - { name: author, label: Author }
      - { name: bio, label: Bio }
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date, default: ''}
      - { name: previewImage, label: Preview Image, widget: image }
      - { name: excerpt, label: Excerpt }
      - { name: tags, label: Tags, widget: list }
      - { name: body, label: Body, widget: markdown }
      - label: SEO
        name: seo
        widget: object
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description }
          - { name: keywords, label: Keywords, widget: list }
  - label: Footer
    name: footer
    files:
      - label: Footer
        name: footer
        file: 'src/data/footer.md'
        public_folder: './assets'
        fields:
          - { label: Title, name: title }
          - { label: Image, name: image, widget: image }
          - label: Media Links
            name: mediaLinks
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Link, name: link }
              - { label: Image, name: image, widget: image }
          - { label: Copyright, name: copyright }
  - label: Technologies
    name: technologies
    files:
      - label: Banner
        name: techBanner
        file: 'src/data/technologies/banner.md'
        public_folder: '../assets'
        fields:
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: Tools
        name: techTools
        file: 'src/data/technologies/tools.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - label: Tools
            name: tools
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
      - label: Partnership
        name: partnership
        file: 'src/data/technologies/partner.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: HelpText, name: helpText }
          - { label: Image, name: image, widget: image }
          - { name: body, label: Body, widget: markdown }
      - label: SEO
        name: techSeo
        file: 'src/data/technologies/seo.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
  - label: About
    name: about
    files:
      - label: Banner
        name: aboutBanner
        file: 'src/data/about/banner.md'
        public_folder: '../assets'
        fields:
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: Highlights
        name: highlights
        file: 'src/data/about/highlights.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Highlights
            name: highlights
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Count, name: count }
              - { label: Image, name: image, widget: image }
      - label: SEO
        name: aboutSeo
        file: 'src/data/about/seo.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
  - name: works
    label: Works
    label_singular: 'Works'
    folder: src/data/works
    slug: '{{slug}}'
    create: true
    media_folder: ''
    public_folder: ''
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: image, label: Image, widget: image }
      - { name: theme, label: Theme }
      - { name: categories, label: Categories, widget: list }
      - label: Tags
        name: workTags
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: themeColor, label: Theme Color }
          - { name: themeBg, label: Theme Background }
      - label: SEO
        name: seo
        widget: object
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description }
          - { name: keywords, label: Keywords, widget: list }
