backend:
  name: gitlab
  repo: fidisys/website/web-revamp

publish_mode: editorial_workflow

media_folder: 'src/data/assets'
public_folder: '/'

collections:
  - label: Home
    name: home
    files:
      - label: Banner
        name: homeBanner
        file: 'src/data/home/banner.md'
        public_folder: '../assets'
        fields:
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: Services
        name: homeServices
        file: 'src/data/home/services.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Services
            name: services
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
      - label: Clients
        name: homeClients
        file: 'src/data/home/clients.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Clients
            name: clients
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Image, name: image, widget: image }
      - label: Works
        name: homeWorks
        file: 'src/data/home/works.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - label: Works
            name: works
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Description, name: description }
              - { name: type, label: Type, widget: "select", options: ["casestudy", "website"] }
              - { label: Link, name: link }
              - { label: Image, name: image, widget: image }
      - label: SEO
        name: homeSeo
        file: 'src/data/home/seo.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
  - label: Testimonials
    name: testimonials
    files:
      - label: Testimonials
        name: testimonials
        file: 'src/data/testimonials.md'
        public_folder: './assets'
        fields:
          - { label: Title, name: title }
          - label: Customers
            name: customers
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Name, name: name }
              - { label: Message, name: message }
              - { label: Comment, name: comment }
              - { label: Role, name: role }
              - { label: Company, name: company }
              - { label: Image, name: image, widget: image }
  - name: blog
    label: Blog
    label_singular: 'Blog'
    folder: src/data/blog
    slug: '{{slug}}'
    create: true
    media_folder: ''
    public_folder: ''
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { name: authImg, label: Preview Image, widget: image }
      - { name: author, label: Author }
      - { name: bio, label: Bio }
      - { name: title, label: Title }
      - { name: linkdin, label: Linkdin, required: false }
      - { name: twitter, label: Twitter, required: false }
      - { name: date, label: Date, widget: datetime, default: '' }
      - { name: previewImages, label: Card Preview Image, widget: image }
      - { name: previewTitle, label: Blog Category Tag, widget: "select", options: ["Frontend Development", "Backend Development", "Full Stack"], required: false }
      - { name: excerpt, label: Excerpt }
      - { name: body, label: Body, widget: markdown }
      - label: SEO
        name: seo
        widget: object
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description }
          - { name: keywords, label: Keywords, widget: list }
  - label: Footer
    name: footer
    files:
      - label: Footer
        name: footer
        file: 'src/data/footer.md'
        public_folder: './assets'
        fields:
          - { label: Title, name: title }
          - { label: Image, name: image, widget: image }
  - label: Services
    name: services
    files:
      - label: Banner
        name: techBanner
        file: 'src/data/services/banner.md'
        public_folder: '../assets'
        fields:
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: Tools
        name: techTools
        file: 'src/data/services/tools.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - label: Technologies
            name: technologies
            widget: list
            fields:
              - { label: Title, name: title }
              - { label: Description, name: description }
              - { label: ID, name: id }
              - label: Technologies
                name: technologies
                widget: list
                fields:
                  - { label: Title, name: title }
                  - { label: Image, name: image, widget: image }
      - label: Partnership
        name: partnership
        file: 'src/data/services/partner.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: HelpText, name: helpText }
          - { label: Image, name: image, widget: image }
          - { name: body, label: Body, widget: markdown }
      - label: SEO
        name: techSeo
        file: 'src/data/services/seo.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
  - label: About
    name: about
    files:
      - label: Banner
        name: aboutBanner
        file: 'src/data/about/banner.md'
        public_folder: '../assets'
        fields:
          - { label: Description, name: description }
          - { label: Image, name: image, widget: image }
      - label: Highlights
        name: highlights
        file: 'src/data/about/highlights.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - label: Highlights
            name: highlights
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Count, name: count }
              - { label: Image, name: image, widget: image }
      - label: Activities
        name: activities
        file: 'src/data/about/activities.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - label: Activities
            name: activities
            widget: list
            fields:
              - { label: ID, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Description, name: description }
              - { label: Nav Id, name: navId }
              - { label: Link, name: link }
              - { label: Image, name: image, widget: image }
      - label: Fidishow
        name: fidishow
        file: 'src/data/about/fidishow.md'
        public_folder: '../assets'
        fields:
          - { label: Title, name: title }
          - { label: Help Text, name: helpText }
          - { label: Author, name: showAuthor, widget: image }
          - { label: Platform Logo, name: pfLogo, widget: image }
          - { label: Nav Id, name: navId }
          - { label: Link, name: link }
          - { label: Image, name: image, widget: image }
          - { name: body, label: Body, widget: markdown }
      - label: SEO
        name: aboutSeo
        file: 'src/data/about/seo.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
  - name: works
    label: Works
    label_singular: 'Works'
    folder: src/data/works
    slug: '{{slug}}'
    create: true
    media_folder: ''
    public_folder: ''
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: image, label: Image, widget: image, required: false }
      - { name: theme, label: Theme }
      - { name: categories, label: Categories, widget: "select", options: ["mobileapp", "ui-ux", "websites"] }
      - label: Tags
        name: workTags
        widget: list
        fields:
          - { name: title, label: Title }
          - { name: themeColor, label: Theme Color }
          - { name: themeBg, label: Theme Background }
      - { name: type, label: Type, widget: "select", options: ["casestudy", "website"] }
      - { name: pageLink, label: Page Link, required: false }
      - { name: appLogo, label: App Logo, widget: image, required: false }
      - { name: bannerImage, label: Banner Image, widget: image, required: false }
      - { name: bannerBackgroundImage, label: Banner background Image, widget: image, required: false }
      - label: Review
        name: review
        widget: object
        required: false
        fields:
          - { label: Rating, name: rating, widget: "number", required: false, min: 1, max: 5 }
          - { label: Comment, name: comment, required: false }
          - { label: Username, name: username, required: false }
      - { name: body, label: Body, widget: markdown, required: false }
      - label: SEO
        name: seo
        widget: object
        fields:
          - { name: title, label: Title }
          - { name: description, label: Description }
          - { name: keywords, label: Keywords, widget: list }
  - label: SEO Blog Page
    name: seoBlog
    files:
      - label: SEO Blog
        name: seoBlog
        file: 'src/data/seoBlog.md'
        fields:
          - { label: Title, name: title }
          - { label: Description, name: description }
          - { label: Keywords, name: keywords, widget: list }
  - label: Social Media Links
    name: socialMediaLinks
    files:
      - label: Social Media Links
        name: socialMediaLinks
        file: 'src/data/smLinks.md'
        public_folder: './assets'
        fields:
          - { label: Title, name: title }
          - label: Media Links
            name: mediaLinks
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Link, name: link }
              - { label: Image, name: image, widget: image }
  - label: Sitemap
    name: sitemap
    files:
      - label: Sitemap
        name: sitemap
        file: 'src/data/sitemap.md'
        fields:
          - { label: Title, name: title }
          - label: SitemapList
            name: sitemapList
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Title, name: title }
              - label: Sitemap
                name: sitemap
                widget: list
                fields:
                  - { label: id, name: id, widget: number }
                  - { label: Title, name: title }
                  - { label: Link, name: link }
          - { label: Copyright, name: copyright }
  - label: Contact
    name: contact
    files:
      - label: Contact
        name: contact
        file: 'src/data/contact.md'
        public_folder: './assets'
        fields:
          - { label: Title, name: title }
          - label: Contact
            name: contact
            widget: list
            fields:
              - { label: id, name: id, widget: number }
              - { label: Title, name: title }
              - { label: Info, name: info }
              - { label: Image, name: image, widget: image }
          - { name: body, label: Body, widget: markdown }
